default_language_version:
  # force all unspecified python hooks to run python3.11
  python: python3.11

files: .
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
- repo: local
  hooks:
  - id: isort
    name: isort (python)
    entry: python -m isort
    args: [--settings-path=./pyproject.toml]
    language: system
- repo: local
  hooks:
  - id: black
    name: black
    entry: python -m black
    language: system
    types: [python]
    args: [--config=./pyproject.toml]
    verbose: true
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.8
  hooks:
  # Run the linter.
  - id: ruff
    args: [--fix]
  # Run the formatter.
  - id: ruff-format
