train:
  source_data: "./training/data/uWaveGestures.parquet"
  input_dim: 48
  hidden_dims: [128, 64, 32] # create a 3 hiden layers model
  output_dim: 8
  batch_size: 16
  learning_rate: 0.01
  momentum: 0.9
  num_epochs: 100
  model_root_path: './training/models'
  train_data_root_path: './training/data/preprocessed_train_data/'
  test_data_root_path: './training/data/preprocessed_test_data/'

test:
  path_to_test_data: './training/data/preprocessed_test_data/'
  base_path_to_model: './training/models'

extend_data:
  path_to_extend_data: "./training/data/uWaveGestures_2extend.parquet"
